upload_max_filesize = 12M
post_max_size = 14M
max_execution_time = 300
memory_limit = 256M
expose_php = Off
display_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED
session.cookie_httponly = 1
session.use_strict_mode = 1
date.timezone = UTC
opcache.enable = 1
opcache.validate_timestamps = 0
