<?php

namespace App\Enums;

enum AuditEvent: string
{
    case SMS_RECEIVED = 'SMS_RECEIVED';
    case SMS_PARSED = 'SMS_PARSED';
    case SMS_UPLOADED = 'SMS_UPLOADED';
    case SMS_DUPLICATE_REJECTED = 'SMS_DUPLICATE_REJECTED';
    case RECEIPT_UPLOADED = 'RECEIPT_UPLOADED';
    case OCR_STARTED = 'OCR_STARTED';
    case OCR_COMPLETED = 'OCR_COMPLETED';
    case OCR_FAILED = 'OCR_FAILED';
    case MATCH_STARTED = 'MATCH_STARTED';
    case MATCH_COMPLETED = 'MATCH_COMPLETED';
    case PAYMENT_VERIFIED = 'PAYMENT_VERIFIED';
    case PAYMENT_REJECTED = 'PAYMENT_REJECTED';
    case PAYMENT_SENT_TO_REVIEW = 'PAYMENT_SENT_TO_REVIEW';
    case PAYMENT_STATUS_CHANGED = 'PAYMENT_STATUS_CHANGED';
    case ADMIN_APPROVED = 'ADMIN_APPROVED';
    case ADMIN_REJECTED = 'ADMIN_REJECTED';
    case ADMIN_REVIEW_REQUEST = 'ADMIN_REVIEW_REQUEST';
    case TELEGRAM_MESSAGE_RECEIVED = 'TELEGRAM_MESSAGE_RECEIVED';
    case TELEGRAM_LINKED = 'TELEGRAM_LINKED';
    case DEVICE_REGISTERED = 'DEVICE_REGISTERED';
    case DEVICE_AUTH_FAILED = 'DEVICE_AUTH_FAILED';
    case SETTING_CHANGED = 'SETTING_CHANGED';
    case BANK_CONFIG_CHANGED = 'BANK_CONFIG_CHANGED';
    case FRAUD_FLAG = 'FRAUD_FLAG';
}
